# Generated by Django 4.1.2 on 2022-10-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="categories",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="contributors",
            new_name="contributor",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="users",
            new_name="user",
        ),
        migrations.AddField(
            model_name="userbook",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
