# Generated by Django 4.1.2 on 2022-10-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_book_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.language",
            ),
        ),
    ]
